// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BeSpokedSalesModel.DBModels;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public DateOnly StartDate { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}