// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BeSpokedSalesModel.DBModels;

public partial class Product
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public string Manufacturer { get; set; }

    public string Style { get; set; }

    public decimal PurchasePrice { get; set; }

    public decimal SalePrice { get; set; }

    public int QtyOnHand { get; set; }

    public decimal CommissionPercentage { get; set; }

    public virtual ICollection<Discount> Discounts { get; set; } = new List<Discount>();

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}