// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BeSpokedSalesModel.DBModels;

public partial class Salesperson
{
    public int SalespersonId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? TerminationDate { get; set; }

    public int? ManagerId { get; set; }

    public virtual ICollection<Salesperson> InverseManager { get; set; } = new List<Salesperson>();

    public virtual Salesperson Manager { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}